export const HEADER_SCROLLED_OFFSET = 10;

export const REVEAL_THRESHOLD = 0.08;
export const REVEAL_ROOT_MARGIN = '0px 0px -40px 0px';

export const LIQUID_BUTTON_MAX_TRANSLATE = 10;
export const LIQUID_BUTTON_MAX_ROTATE = 7;
export const LIQUID_BUTTON_HOVER_SCALE = 1.04;
export const LIQUID_BUTTON_PRESS_SCALE = 0.97;
export const LIQUID_BUTTON_FLOAT_Y = -4;
export const LIQUID_BUTTON_FLOAT_DURATION = 2.6;
export const LIQUID_BUTTON_SETTLE_DURATION = 0.45;
export const LIQUID_BUTTON_MOVE_DURATION = 0.35;

export const PAGE_TRANSITION_DURATION = 0.62;
export const PAGE_TRANSITION_ENTER_DURATION = 0.8;
export const PAGE_SCROLL_REVEAL_START = 'top 82%';

export const RECENT_CAROUSEL_CENTER_RATIO = 0.55;
export const RECENT_CAROUSEL_BASE_SCALE = 0.92;
export const RECENT_CAROUSEL_SCALE_BOOST = 0.1;
export const RECENT_CAROUSEL_VERTICAL_LIFT = 14;
export const RECENT_CAROUSEL_BASE_OPACITY = 0.58;
export const RECENT_CAROUSEL_OPACITY_BOOST = 0.42;
export const RECENT_CAROUSEL_ACTIVE_THRESHOLD = 0.84;
export const RECENT_CAROUSEL_MIN_DURATION = 28;
export const RECENT_CAROUSEL_PIXELS_PER_SECOND = 48;